version: 2

jobs:
  test_and_stylecheck:
    docker:
      - image: circleci/node:10.15.2
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run ci
  build_deploy:
    docker:
      - image: circleci/node:10.15.2
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "89:58:dc:59:20:ad:6e:0a:01:3b:63:e9:f9:3a:fa:44"
      - run: npm run deploy

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - test_and_stylecheck:
            filters:
              branches:
                ignore: gh-pages
        - build_deploy:
            requires:
              - test_and_stylecheck
            filters:
              branches:
                ignore: gh-pages
